/* auto-generated by NAPI-RS */
/* eslint-disable */
/** An evolutionary search driven by JSON commands. */
export declare class Darwin {
  /**
   * Construct a search handle from a spec JSON (`"{}"` defers configuration
   * to a later `set_spec` command). Throws on an invalid spec.
   */
  constructor(specJson: string)
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Commands: `set_spec`, `evolve`, `best`, `version`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
